WebApi + React App
WSWCWaterDataExchange/WestDAAT pull request #26
Opened 2022-02-15 22:22 UTC by bbarber

A lot of boilerplate code to get up and running with a Database / Api / React site

2022-02-15 22:24 UTC, bbarber commented
Sample solution contains a dummy end-to-end test with "Todo" items. This will be used to test our QA deployments, to ensure we have a valid test from UI -> API -> Database. This will get removed after testing

2022-02-17 18:51 UTC, Rhipeus requested changes
Also, namespace change to WesternStatesWater.WestDaat

2022-02-17 18:51 UTC, Rhipeus commented on pipelines/on-merge-angular-develop.yml
> +trigger:
I don't believe we need this angular file from the template.  Can we ditch it?

2022-02-17 18:51 UTC, Rhipeus commented on pipelines/on-merge-angular-staging.yml
> +trigger:
I don't believe we need this angular file from the template.  Can we ditch it?

2022-02-17 18:51 UTC, Rhipeus commented on pipelines/pr-angular.yml
> +trigger:
I don't believe we need this angular file from the template.  Can we ditch it?

2022-02-17 19:45 UTC, bbarber commented
<img width="352" alt="image" src="https://user-images.githubusercontent.com/613184/154558839-3144ed8f-7308-443f-b698-c39122ac87b7.png">

I am blessed to merge my own PR

2022-02-17 19:46 UTC, bbarber commented on pipelines/pr-angular.yml
> +trigger:
Ditched in next PR

2022-02-17 19:46 UTC, merged