Geoconnex Api
WSWCWaterDataExchange/WestDAAT pull request #34
Opened 2022-03-02 20:11 UTC by bbarber

2022-03-02 21:10 UTC, Rhipeus requested changes

2022-03-02 21:10 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Engines/Resources/GeoConnexJsonTemplate.json
> +    "gsp:asWKT": "POINT ({0} {1})"
Some sites have an actual polygon geometry.  I assume that we'd want to use that if we have it.

2022-03-02 21:10 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Accessors/ISiteAccessor.cs
> +        SitesDim GetWaterAllocationSiteDetailsById(string id);
let's call this `siteUuid` instead of just `id`

2022-03-02 21:10 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Engines/GeoConnexEngine.cs
> +            var geoConnexJson = string.Format(GeoConnexResources.GeoConnexJsonTemplate,
We may need to escape some of these values to avoid malformed JSON.  I'm not 100% sure what all values could end up in some of these fields.

2022-03-02 21:22 UTC, bbarber commented on src/API/WesternStatesWater.WestDaat.Engines/Resources/GeoConnexJsonTemplate.json
> +    "gsp:asWKT": "POINT ({0} {1})"
Good catch, although I have 145955 records with null geometry, and 2 records with non-null geometries. Is this expected?

2022-03-04 04:58 UTC, bbarber commented on src/API/WesternStatesWater.WestDaat.Engines/GeoConnexEngine.cs
> +            var geoConnexJson = string.Format(GeoConnexResources.GeoConnexJsonTemplate,
Done

2022-03-04 12:41 UTC, Rhipeus requested changes

2022-03-04 12:41 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Engines/GeoConnexEngine.cs
> +                    site.Geometry?.ToString()       // {10}
Sorry - I probably wasn't clear here.  If we have the geometry we should use it.  Otherwise, we should fall back to the "POINT(long lat)" you had.

2022-03-04 12:41 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Tests.AccessorTests/WaterAllocationAccessorTests.cs
> +            var site = new SitesDimFaker().Generate();
Can we skip creating the sites here and just generate the WaterAllocation directly?

2022-03-04 12:41 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Engines/Resources/GeoConnexJsonTemplate.json
> +    "gsp:asWKT": "POINT ({0} {1})"
That is probably correct

2022-03-04 12:42 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Engines/GeoConnexEngine.cs
> +                    site.Geometry?.ToString()       // {10}
This point is already going to be in the SitePoint field

2022-03-04 13:30 UTC, Rhipeus approved these changes

2022-03-04 13:30 UTC, merged