Add Admin / Conservation manager
WSWCWaterDataExchange/WestDAAT pull request #403
Opened 2024-12-18 20:47 UTC by bbarber

Pull Request Checklist

- [ ] Did you pull latest and merge `develop` (or `master`) into your branch?
- [ ] Did you add tests?
- [ ] Did you run the front-end tests (if applicable)?
- [ ] Did you run the back-end tests (if applicable)?
- [ ] Did you include screenshots or a demo video (if applicable)?
- [ ] Did you include a descriptive title and description with your PR?
- [ ] Did you perform a self-review before assigning reviewers?

2024-12-18 21:38 UTC, bbarber commented on src/API/WesternStatesWater.WestDaat.Tests.IntegrationTests/Conservation/ApplicationIntegrationTests.cs
> +}
Intentionally left empty until proxy pattern is established

2024-12-19 14:11 UTC, tarrball requested changes

2024-12-19 17:30 UTC, bbarber commented on src/API/WesternStatesWater.WestDaat.Contracts.Client/IApplicationManager.cs
> +    Task<ResponseBase> Store(RequestBase request);
Thoughts on this dir / namespace?
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/4ab730f5-c823-4de8-b68c-efec614ad708" />

2024-12-19 17:35 UTC, bbarber commented on src/API/WesternStatesWater.WestDaat.Contracts.Client/IApplicationManager.cs
> +    Task<ResponseBase> Store(RequestBase request);
Pushed

2024-12-19 17:35 UTC, bbarber commented on src/API/WesternStatesWater.WestDaat.Client.Functions/Program.cs
> +        services.AddScoped<IUserManager, AdminManager>();
Agree - Updated to use `AddTransient`

2024-12-19 18:42 UTC, tarrball approved these changes

2024-12-19 18:42 UTC, merged