Water Right Details Page
WSWCWaterDataExchange/WestDAAT pull request #49
Opened 2022-03-16 14:57 UTC by jeffkodad

2022-03-16 21:06 UTC, bbarber requested changes

2022-03-16 21:06 UTC, bbarber commented on src/DashboardUI/src/components/WaterRightTabs.tsx
> +                            <tr>
I'm surprised that react isn't throwing a warning about needing a `key` property. Maybe there's only one??
https://reactjs.org/docs/lists-and-keys.html

2022-03-16 21:06 UTC, bbarber commented on src/DashboardUI/src/pages/DetailsPage.tsx
> +    return (
If it's not too much effort, would you mind adding a screenshot to help review the UI portions?

2022-03-16 21:06 UTC, bbarber commented on src/DashboardUI/src/styles/detail-page.scss
> +  background-color: white;
I'd probably move all the colors in this file to the `_colors.scss` file. For this specific background color, feel free to nuke the override that was setting it to gray. I think it was left over from testing the variable overrides with bootstrap

2022-03-16 21:27 UTC, bbarber commented on src/API/WesternStatesWater.WestDaat.Managers/WaterAllocationManager.cs
> +        }
Include unit tests for these

2022-03-16 22:03 UTC, jeffkodad commented
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/20817467/158698797-631dc004-dee0-4de7-abcd-ec4c663b0dfb.png">
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/20817467/158698830-d671b63d-b56c-4896-9239-1eefc4ec5e92.png">

2022-03-17 13:26 UTC, Rhipeus requested changes

2022-03-17 13:26 UTC, Rhipeus commented on src/DashboardUI/src/components/WaterRightProperties.tsx
> +    const waterRightDetails = useWaterRightDetails(+props.waterRightId).data;
We probably need to display something while this loads.  However, I have an upcoming branch that includes a hook to help handle this.  Make note that we need to add something here for that and we'll get it included later.

2022-03-17 13:26 UTC, Rhipeus commented on src/DashboardUI/src/hooks/waterAllocation.ts
> +import { useQuery } from 'react-query';
I like this pattern for data retrieval!

🎉

2022-03-17 13:26 UTC, Rhipeus commented on src/DashboardUI/src/pages/DetailLayout.tsx
> +// TODO: Do we need logic to redirect if we don't have detail type or detail id in route?
probably but quite sure how that should work.  There could be some hope in an adaptation of something like:
https://stackoverflow.com/a/68798640/4552551

2022-03-17 18:21 UTC, jeffkodad commented on src/API/WesternStatesWater.WestDaat.Accessors/IWaterAllocationAccessor.cs
> +        Task<WaterSourceInfoListItem[]> GetWaterRightSourceInfoById(long waterRightId);
Updated to Lists.

2022-03-17 18:22 UTC, jeffkodad commented on src/API/WesternStatesWater.WestDaat.Common/DataContracts/WaterRightDetails.cs
> +        public string AmountUnitCv { get; set; }
Updated data contracts.

2022-03-17 18:22 UTC, jeffkodad commented on src/DashboardUI/src/components/SiteMap.tsx
> +    return <div>
Updated.

2022-03-17 18:22 UTC, jeffkodad commented on src/DashboardUI/src/pages/DetailsPage.tsx
> +  detailType: string;
Updated.

2022-03-17 18:22 UTC, jeffkodad commented on src/DashboardUI/src/components/WaterRightTabs.tsx
> +                            <tr>
Updated.

2022-03-17 18:22 UTC, jeffkodad commented on src/DashboardUI/src/pages/DetailsPage.tsx
> +    return (
Added.

2022-03-17 18:23 UTC, jeffkodad commented on src/API/WesternStatesWater.WestDaat.Managers/WaterAllocationManager.cs
> +        }
Added.

2022-03-17 18:33 UTC, jeffkodad commented on src/API/WesternStatesWater.WestDaat.Accessors/SiteAccessor.cs
> +                return db.SitesDim
Updated

2022-03-17 18:34 UTC, jeffkodad commented on src/API/WesternStatesWater.WestDaat.Accessors/WaterAllocationAccessor.cs
> +            var bridges = await db.AllocationBridgeSitesFact.Where(x => x.AllocationAmountId == waterRightId)
I was having issues getting the distince to work with the geometry properties, I was finally able to get DistinctBy to work using the uuid as the key property. Hopefully this will get the items unique.

2022-03-17 18:35 UTC, jeffkodad commented on src/API/WesternStatesWater.WestDaat.Common/DataContracts/WaterRightDetails.cs
> +        public double? AllocationFlow_CFS { get; set; }
Updated.

2022-03-17 18:42 UTC, jeffkodad commented on src/API/WesternStatesWater.WestDaat.Common/DataContracts/WaterRightDetails.cs
> +        public double? AllocationFlow_CFS { get; set; }
Updated

2022-03-17 18:44 UTC, jeffkodad commented on src/API/WesternStatesWater.WestDaat.Tests.Helpers/FakerExtensions.cs
> +        public static Faker<AllocationBridgeSitesFact> AllocationBridgeSiteFactFakerWithIds(this IRuleSet<AllocationBridgeSitesFact> faker, long allocationId, long siteId)
These extension classes need to be static and within static classes to function as exceptions to the standard faker rules. This follows the pattern of faker exceptions that Zach used in previous projects using deep faker methods for unit tests.

2022-03-17 18:44 UTC, jeffkodad commented on src/DashboardUI/src/components/WaterRightProperties.tsx
> +    const waterRightDetails = useWaterRightDetails(+props.waterRightId).data;
Note added.

2022-03-17 18:44 UTC, jeffkodad commented on src/DashboardUI/src/hooks/waterAllocation.ts
> +import { useQuery } from 'react-query';
All credit to Beebs.

2022-03-18 11:52 UTC, Rhipeus commented on src/DashboardUI/src/components/WaterRightTabs.tsx
> +                <tr key={i}>
The siteUuid would be slightly better to use here.  When we have a unique key available, we should use it.  That allows React to reuse dom elements better when it redraws.  Instead of rebuilding most of element, it will instead move the element if the key stays the same.  It probably doesn't make a huge difference here but it can when the elements being redrawn are more complex (i.e. images or deep HTML).

2022-03-18 11:52 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Tests.Helpers/FakerExtensions.cs
> +        public static Faker<AllocationBridgeSitesFact> AllocationBridgeSiteFactFakerWithIds(this IRuleSet<AllocationBridgeSitesFact> faker, long allocationId, long siteId)
The static class methods should be used for more generic helpers.  In WestDAAT, things like how to build a CV "name" or geometry data would be good static methods.

In this case, these are closely related to their types.  There isn't any reuse here for other places.  Thus, they can go directly onto the classes as non-static methods.

2022-03-18 11:53 UTC, Rhipeus approved these changes

2022-03-18 11:54 UTC, Rhipeus commented
Clean up just a couple small things then go ahead and merge.

2022-03-18 14:58 UTC, jeffkodad commented on src/DashboardUI/src/components/WaterRightTabs.tsx
> +                <tr key={i}>
Updated

2022-03-18 15:04 UTC, jeffkodad commented on src/API/WesternStatesWater.WestDaat.Accessors/Mapping/ApiProfile.cs
> +                .ForMember(dest => dest.BeneficialUse, opt => opt.MapFrom(source => source.PrimaryBeneficialUse.Name))
Confirmed with the WSWC guys, WaDEName is the one to use here.

2022-03-18 15:18 UTC, bbarber approved these changes

2022-03-18 16:35 UTC, merged