Kodad water right details map
WSWCWaterDataExchange/WestDAAT pull request #54
Opened 2022-03-22 18:29 UTC by jeffkodad

![image](https://user-images.githubusercontent.com/20817467/159545967-eda6136a-3599-49dd-b4e0-e31086a49b0c.png)

![image](https://user-images.githubusercontent.com/20817467/159546060-5a635bdd-8d72-495a-9a98-4da6e246965d.png)

2022-03-22 19:48 UTC, Rhipeus requested changes

2022-03-22 19:48 UTC, Rhipeus commented on src/DashboardUI/src/components/Map.tsx
> +      padding: 50,
Should we also be able to pass in padding and maxZoom?

2022-03-23 20:23 UTC, jeffkodad commented on src/API/WesternStatesWater.WestDaat.Managers/WaterAllocationManager.cs
> +        public async Task<List<SiteLocation>> GetWaterRightSiteLocations(long waterRightsId)
Updated.

2022-03-23 20:23 UTC, jeffkodad commented on src/DashboardUI/src/components/WaterRightMap.tsx
> +  const waterRightSiteLocations = useWaterRightSiteLocations(+props.waterRightId).data;
Added.

2022-03-23 20:27 UTC, jeffkodad commented on src/DashboardUI/src/components/Map.tsx
> +    const bounds = new mapboxgl.LngLatBounds(mapBounds[0], mapBounds[0]);
Yup, the bounds object wants the two opposing corners for coordinates so we give it the same point first before extending to each additional point. This way we don't have to order the points or figure out the corners on our own.

2022-03-23 20:27 UTC, jeffkodad commented on src/DashboardUI/src/components/Map.tsx
> +      padding: 50,
Updated to include those two props.

2022-03-23 20:44 UTC, jeffkodad commented on src/DashboardUI/src/config/maps.ts
> +        "circle-color": "#01579b"
Updated

2022-03-24 15:08 UTC, Rhipeus approved these changes

2022-03-24 15:08 UTC, merged