Show disclaimer on first viewing only
WSWCWaterDataExchange/WestDAAT pull request #91
Opened 2022-05-09 18:18 UTC by goldilocked

Displaying existing disclaimer modal on home page when first navigating to the page. Setting a value in localStorage when the disclaimer modal "okay" button is pressed. Using that value to not show the disclaimer modal on future visits to the page.

2022-05-09 19:31 UTC, EverettRhodes approved these changes

2022-05-09 19:34 UTC, Rhipeus requested changes
I think we want to move this code off of the homepage and onto the layout somewhere.  The reason is that we want them to have to accept the disclaimer if they hit one of the landing/detail pages before they hit the home page (maybe they were shared a link to the landing page for instance).

2022-05-09 19:34 UTC, Rhipeus commented on src/DashboardUI/src/components/DisclaimerModal.tsx
> +    localStorage.setItem("disclaimer", "donotshow");
What if we make this a "disclaimer acceptance date" type of thing here.  Thinking about this, we may want to in the future update the disclaimer and have them reaccept it.  A date would give us that flexibility.

2022-05-09 19:34 UTC, Rhipeus commented on src/DashboardUI/src/components/DisclaimerModal.tsx
>      props.setShow(false);
It is probably a little better here to have an `acceptDisclaimer` pass in the props.  On close, the DisclaimerModal would just call that.  Then in the calling component, it would set the local storage item and set the boolean to hide the modal.

2022-05-11 15:19 UTC, Rhipeus commented on src/DashboardUI/src/components/DisclaimerModal.tsx
>      props.setShow(false);
:+1: - nailed it

2022-05-11 15:20 UTC, merged