feedback modal, emails
WSWCWaterDataExchange/WestDAAT pull request #94
Opened 2022-05-12 00:30 UTC by rsimosa

Adding Feedback modal and thankyou modals
Added a check for not sending any information to the backEnd if the form has no input
Added SendGrid to send feedback to an email
Added Unit Tests for the notification Manager

![image](https://user-images.githubusercontent.com/64144574/167967913-21c19aa4-5b10-4dc6-a22d-49c06d87f596.png)
![image](https://user-images.githubusercontent.com/64144574/167968636-fe1b2c04-be86-499d-9bc4-e960045d13a6.png)

2022-05-12 15:13 UTC, Rhipeus requested changes

2022-05-12 15:13 UTC, Rhipeus commented on src/DashboardUI/src/components/SiteFooter.tsx
> +            <Nav.Link className="p-0" target="_blank"  href="#" onClick={() => props.showFeedbackModal(true)}> Feedback </Nav.Link>
This should be a button and not a link

2022-05-12 15:17 UTC, rsimosa commented on src/API/WesternStatesWater.WestDaat.Managers/NotificationManager.cs
> +                emailAddresses.Add(request.Email?.Trim());
Adel required to send the email to the requestor
![image](https://user-images.githubusercontent.com/64144574/168109384-83f0c4c2-78af-4401-b323-a0dd926c5fe1.png)

2022-05-12 15:50 UTC, rsimosa commented on src/API/WesternStatesWater.WestDaat.Utilities/EmailNotificationSDK.cs
> +                _logger.LogError($"Something went wrong while sending feedback email.\nStatusCode: {response.StatusCode}.\nMessageBody: {message.Body}.");
I did it this way to keep the message body and keep the feedback, as I only see it failing if we do more than the free tier allowed messages or SendGrid is down

2022-05-12 16:22 UTC, rsimosa commented on src/API/WesternStatesWater.WestDaat.Managers/NotificationManager.cs
> +        private string FeedbackMessageBody(FeedbackRequest request)
sendGrid is ignoring the line breaks `\n` and it was displaying it as a single continuous string
![image](https://user-images.githubusercontent.com/64144574/168122222-f39ac216-26f8-4782-9f5e-045b144626cd.png)

that's why I was using a basic html format, if we are okay with using a continous single String I am okay with removing the html markup I added.

else I will update to use string replacements and decoding or create a regex whitelist characters

2022-05-12 18:53 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Managers/NotificationManager.cs
> +        private string FeedbackMessageBody(FeedbackRequest request)
Were you doing `\r\n` or `\n` only?  It should be \r\n.

Also, according to random stackoverflow user, SendGrid has a field to specify text vs html (https://stackoverflow.com/questions/55852805/send-grid-allow-line-breaks-in-emails-with-plain-text).  If so, make sure it is set to text.

2022-05-12 19:17 UTC, rsimosa commented on src/API/WesternStatesWater.WestDaat.Managers/NotificationManager.cs
> +            var emailAddresses = new List<string> { "adelabdallah@wswc.utah.gov", "rjames@wswc.utah.gov" };
updated

2022-05-12 19:17 UTC, rsimosa commented on src/API/WesternStatesWater.WestDaat.Common/Configuration/ConfigurationHelper.cs
> +        public const string SendGrid = "SendGrid";
updated

2022-05-12 19:18 UTC, rsimosa commented on src/API/WesternStatesWater.WestDaat.Managers/NotificationManager.cs
> +        private string FeedbackMessageBody(FeedbackRequest request)
I was only using the `\n` adding the `\r\n` fixed it Thanks

2022-05-12 19:18 UTC, rsimosa commented on src/API/WesternStatesWater.WestDaat.Managers/NotificationManager.cs
> +                emailAddresses.Add(request.Email?.Trim());
updated, from latest teams msg

2022-05-12 19:18 UTC, rsimosa commented on src/API/WesternStatesWater.WestDaat.Tests.ManagerTests/NotificationManagerTests.cs
> +        public async Task SendFeedback_DoesNotAddEmailToList(string invalidEmail)
updated

2022-05-12 19:19 UTC, rsimosa commented on src/DashboardUI/src/components/SiteFooter.tsx
> +            <Nav.Link className="p-0" target="_blank"  href="#" onClick={() => props.showFeedbackModal(true)}> Feedback </Nav.Link>
updated

2022-05-12 19:56 UTC, Rhipeus submitted a review, later dismissed

2022-05-12 19:56 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Client.Functions/Startup.cs
> +            builder.Services.AddScoped(a => configuration.GetSMTPConfiguration());
Acronyms 3 characters or longer should be camel-cased.  All the "SMTP"s should be "Smtp"

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

2022-05-12 19:56 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Client.Functions/Startup.cs
> +            builder.Services.AddTransient<IEmailNotificationSDK, EmailNotificationSDK>();
The casing would apply to SDK here also

2022-05-12 19:56 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Utilities/EmailNotificationSDK.cs
> +        public async void SendFeedback(CommonDTO.EmailRequest message)
We went too far with making this not return a success boolean.  The async/await task stuff was still appropriate and helpful.  We just shouldn't have been returning the boolean.

2022-05-12 19:56 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Utilities/EmailNotificationSDK.cs
> +            catch (Exception ex)
We shouldn't be catching.  Let this go up the stack.

2022-05-12 19:56 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Client.Functions/System.cs
> -            return new OkResult();
We should still be returning an `OkResult` object here

2022-05-12 19:56 UTC, Rhipeus commented on src/DashboardUI/src/components/SiteFooter.tsx
> +            <button type="button" className="p-0 btn btn-text-color" onClick={() => props.showFeedbackModal(true)}>  Feedback </button>
Does this look like the link above?  I expected this to have a `btn-link`.  If it looks correct, no worries.

2022-05-12 19:56 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Common/Configuration/EmailServiceConfiguration.cs
>          public string APIKey {get; set;}
All of these properties are needed for this to work.  Yet I don't see any default values setup.  What is the plan for deployment into QA?  Are you manually setting these up?

2022-05-12 19:56 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Contracts.Client/FeedbackRequest.cs
> +        public string Name { get; set; }
Should this be `FirstName`?

2022-05-12 19:56 UTC, Rhipeus commented on src/API/WesternStatesWater.WestDaat.Utilities/IEmailNotificationSDK.cs
> +        void SendFeedback(CommonDTO.EmailRequest message);
`SendEmail` was better.  This method should be generic and not related to any specific message.

2022-05-12 19:56 UTC, Rhipeus commented on src/DashboardUI/src/components/FeedbackModal.tsx
> +            <label className="form-label fw-bolder">Name(Optional)</label>
These too should probably be First Name

2022-05-12 19:56 UTC, Rhipeus commented on src/DashboardUI/src/components/FeedbackModal.tsx
> +                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Is Adel aware he needs to provide text here?

2022-05-13 20:53 UTC, EverettRhodes approved these changes

2022-05-13 20:55 UTC, merged