Skenny/beneficial use add consumption type
WSWCWaterDataExchange/WestDAAT pull request #97
Opened 2022-05-16 18:47 UTC by goldilocked

Backend changes made to add ConsumptionType to a beneficial use. Frontend changes made to allow frontend to function with these backend changes.

2022-05-17 21:07 UTC, EverettRhodes requested changes

2022-05-17 21:07 UTC, EverettRhodes commented on src/API/WesternStatesWater.WestDaat.Managers/SystemManager.cs
> +                         select g.Last();
I did not see a unit test for the scenario this code is trying to handle. Is there a test that setups duplicates, as this code is trying to prevent?

2022-05-18 16:37 UTC, goldilocked commented on .vscode/launch.json
> +{
I figured it out, Dubs made one that's in DashboardUI/.vscode while I must have run the debugger from a few steps up. Removed because only the one in DashboardUI should be needed if I debug from the correct location

2022-05-18 16:45 UTC, goldilocked commented on src/API/WesternStatesWater.WestDaat.Managers/SystemManager.cs
> +                         select g.Last();
Test added in accessor tests

2022-05-18 16:47 UTC, EverettRhodes approved these changes

2022-05-18 16:48 UTC, merged